#!/bin/bash
#############
#This script calls the afni program dicom_hdr to read header information, reads the information 
#and then renames and sorts the files alphabetically
#############

#defaults
sourcedir='./'
destdir='renamed'
tempfile='/tmp/dicomsort.tmp'
rename=0
recurse=1

usage='Usage: dicomsort [-r] [-d destdir] [-s sourcedir] [-n]'
helptxt="dicom sort is a script to sort rename dicom files in alphabetical order according to\n \
series and slice number."

#process command line options
while getopts ":rd:s:n" options; do
  case $options in
    r ) rename=1;;
    d ) destdir=$OPTARG;;
    s ) sourcedir=$OPTARG;;
    n ) recurse=0;;
    h ) echo $usage;;
    \? ) echo $usage
    	 echo "dicom sort is a script to sort rename dicom files in alphabetical"
    	 echo "order according to series and slice number.  "
    	 echo "Options:"
    	 echo "-r: rename files.  Default is to copy."
    	 echo "-d: destination directoroy.  Default is ./renamed ."
    	 echo "-s: source directory.  Default is current directory"
    	 echo "-n: don't recursively descend into subdirectories."
    	 echo "-?: print this help message."
    	 echo "-h: print brief usage message."
         exit 1;;
    * ) echo $usage
          exit 1;;
  esac
done

#check to see if the destdir exists and create it if not
if [ -e $destdir ]  
then
	echo Destination directory exists
else
	echo Creating $destdir
	mkdir $destdir	
fi

echo "Procecessing..."

if [ $recurse -eq 1 ]
then
	files=`find $sourcedir -type f ! -name ".*" ! -iname "DICOMDIR"`
else
	files=`find $sourcedir -type f -maxdepth 1 ! -name ".*" ! -iname "DICOMDIR"`
fi	
	
for f in $files;
do
	echo $f
	dicom_hdr $f > $tempfile 
	
	# make sure it's a dicom file
	if grep 'ERROR:' $tempfile 
	then 
	  continue
	fi
	
	# I shortened the grep patterns and changed the awk delimiter to '//'
	snum=`cat $tempfile | grep "Series Number" | awk -F '//' '{print $3}'`
	anum=`cat $tempfile | grep "Acquisition Number" | awk -F '//' '{print $3}'`
	inum=`cat $tempfile | grep "Instance Number" | awk -F '//' '{print $3}'`
	
	targfile=`printf "%s/dcmS%04.0fA%04.0fI%04.0f\n" $destdir $snum $anum $inum`
	
	echo "Series $snum,  Acquisition $anum,  Instance $inum"
	#cp $f ${destdir}dcmS${snum}A${anum}I${inum}
	
	if [ $rename -eq 1 ]
	then
		echo RENAMING $f to $targfile
		mv $f $targfile
	else
		echo COPYING $f to $targfile
		cp $f $targfile
	fi
	
done
rm $tempfile
echo Renaming Complete

